# Generated by Django 4.0.6 on 2022-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
